format = """
$os\
[ ](fg:colour1 bg:colour2)\
$directory\
[ ](fg:colour2 bg:colour3)\
$git_branch\
$git_status\
[ ](fg:colour3 bg:colour4)\
$python\
$rlang\
[ ](fg:colour4)
[ ](fg:foreground)\
"""

palette = 'everforest'

[palettes.everforest]
colour1 = '#1E2326'
colour2 = '#E67E80'
colour3 = '#E69875'
colour4 = '#DBBC7F'
foreground = '#1E2326'
foreground_dk = '#D3C6AA'

[character]
success_symbol = "[ 󱞩](bold fg:foreground)"
error_symbol = "[ 󱞩](bold fg:#af0000)"

[os]
style = "bold fg:foreground_dk bg:colour1"
disabled = false

[os.symbols]
Fedora = "  "

[directory]
style = "bold bg:colour2 fg:foreground"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bold bg:colour3 fg:foreground"
truncation_length = 10
truncation_symbol = "..."
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
conflicted = "󰞇 "
ahead = " "
behind = " "
diverged = "󰃻 "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = '[++$count ](bold bg:colour3 fg:foreground)'
renamed = " "
deleted = " "
style = "bold bg:colour3 fg:foreground"
format = '([ \[$all_status$ahead_behind\]]($style))'

[python]
symbol = " "
python_binary = ['python']
style = "bold bg:colour4 fg:foreground"
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\) )]($style)'

[rlang]
symbol = " "
style = "bold bg:colour4 fg:foreground"
format = '[$symbol ($version)]($style)'
