live_config_reload = true

import = ["~/.config/alacritty/themes/themes/papercolor_light.toml"]

[window]
opacity = 0.9
blur = true

[font]
normal = {family = "Hasklug Nerd Font", style = "Regular"}
bold = {family = "Hasklug Nerd Font", style = "Bold"}
italic = {family = "Hasklug Nerd Font", style = "Italic"}
bold_italic = {family = "Hasklug Nerd Font", style = "Bold Italic"}
size = 14

[colors]
vi_mode_cursor = { text = "#eeeeee", cursor = "#af0000" }
