live_config_reload = true

import = ["~/.config/alacritty/themes/themes/everforest.toml"]

[window]
opacity = 0.9
blur = true

[font]
normal = {family = "Hasklug Nerd Font", style = "Regular"}
bold = {family = "Hasklug Nerd Font", style = "Bold"}
italic = {family = "Hasklug Nerd Font", style = "Italic"}
bold_italic = {family = "Hasklug Nerd Font", style = "Bold Italic"}
size = 14
